import { lazy, Suspense, useEffect, useState } from "react";
import { track } from "@/lib/track";
import { waUrl } from "@/lib/waScript";
import { bumpIntent, lockFunnel } from "@/lib/funnelLock";
const ChatB2K = lazy(() => import("./ChatB2K").then(m => ({ default: m.ChatB2K })));
export const ChatBubble = () => {
  const [shown, setShown] = useState(false), [open, setOpen] = useState(false), [pulse, setPulse] = useState(false);
  useEffect(() => { const t = setTimeout(() => setShown(true), 3000); return () => clearTimeout(t); }, []);
  useEffect(() => { let lastY = scrollY; let ticking = false; const onScroll = () => { if (ticking) return; ticking = true; requestAnimationFrame(() => { const y = scrollY; if (y < lastY - 4) setShown(true); lastY = y; ticking = false; }); }; addEventListener("scroll", onScroll, { passive: true }); return () => removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { const id = setInterval(() => { setPulse(true); setTimeout(() => setPulse(false), 1500); }, 6000); return () => clearInterval(id); }, []);
  useEffect(() => { const handler = () => { track("chatb2k_open", { source: "global_event" }); setOpen(true); }; addEventListener("open-chatb2k", handler); return () => removeEventListener("open-chatb2k", handler); }, []);
  const handleOpen = () => { track("chatb2k_open", { source: "bubble" }); bumpIntent(6, "bubble_open"); lockFunnel("chatb2k", "bubble", "medium"); setOpen(true); };
  const handleWA = () => { track("whatsapp_click", { source: "bubble" }); bumpIntent(5, "bubble_wa"); lockFunnel("whatsapp", "bubble", "soft"); };
  return <><div className={`fixed right-3 z-[90] transition-opacity duration-500 sm:right-5 ${shown ? "opacity-100" : "pointer-events-none opacity-0"}`} style={{ bottom: "calc(0.75rem + env(safe-area-inset-bottom))", willChange: "opacity", contain: "layout paint" }}><div className="relative">{pulse && <span aria-hidden className="absolute inset-0 -z-10 animate-ping rounded-full bg-gold/40" />}<button onClick={handleOpen} aria-label="Open ChatB2K Advisor" className="group flex items-center gap-2 rounded-full border border-gold/60 bg-noir-900/90 px-3 py-2.5 text-gold shadow-gold backdrop-blur-xl transition hover:bg-noir-800 sm:px-5 sm:py-3"><span className="relative grid h-9 w-9 place-items-center rounded-full bg-gradient-gold text-noir-900"><i className="fa-solid fa-comments" /><span className="absolute -right-0.5 -top-0.5 h-2.5 w-2.5 rounded-full bg-gold ring-2 ring-noir-900 animate-pulse" /></span><span className="hidden text-xs font-bold uppercase tracking-[0.2em] sm:inline">ChatB2K Advisor</span></button><a href={waUrl({ source: "bubble" })} target="_blank" rel="noreferrer" onClick={handleWA} aria-label="WhatsApp ResoFlex" className="absolute -left-1 -top-2 grid h-7 w-7 place-items-center rounded-full border border-gold/50 bg-noir-900 text-[#25D366] shadow-gold"><i className="fa-brands fa-whatsapp text-sm" /></a></div></div><Suspense fallback={null}><ChatB2K open={open} onClose={() => setOpen(false)} /></Suspense></>;
};
